-- Schema for properties table (replacing HousingAds)

CREATE TABLE IF NOT EXISTS "properties" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Legacy CSV Columns
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "price" DECIMAL(15, 2) NOT NULL,
    "location" VARCHAR(255),
    "bedrooms" SMALLINT DEFAULT 0,
    "toilet" SMALLINT DEFAULT 0, -- Maps to bathrooms
    "garage" SMALLINT DEFAULT 0,
    "lt" DECIMAL(10, 2), -- Land Size
    "lb" DECIMAL(10, 2), -- Building Size
    "listing_url" TEXT,
    "image_url" TEXT,
    "source" VARCHAR(50) DEFAULT 'manual',
    
    -- Application Extended Columns
    "title" VARCHAR(255),
    "description" TEXT,
    "user_id" BIGINT DEFAULT 1, -- Default to system user if not specified
    "status" VARCHAR(50) DEFAULT 'active',
    "facilities" TEXT,
    "contact_phone" VARCHAR(20) DEFAULT '08000000000',
    "province" VARCHAR(100) DEFAULT 'Indonesia',
    "postal_code" VARCHAR(10),
    "latitude" DECIMAL(10, 7),
    "longitude" DECIMAL(10, 7)
);

-- Index for faster filtering
CREATE INDEX IF NOT EXISTS idx_properties_location ON "properties" ("location");
CREATE INDEX IF NOT EXISTS idx_properties_price ON "properties" ("price");
